/**
 * Widget Account Switcher Implementation
 * 
 * ✅ CRITICAL RULES:
 * 1. Widget talks ONLY to IDP, never to client
 * 2. postMessage with strict types, nonce, requestId
 * 3. CSRF token read from cookie, sent in body
 * 4. Third-party cookie fallback
 * 5. Button lock prevents spam while request in flight
 */

import crypto from "crypto";

// ============================================================================
// Configuration
// ============================================================================

const IDP_URL = process.env.NEXT_PUBLIC_IDP_SERVER || "http://localhost:3000";

// Allowed parent origins (clients that can embed widget)
const ALLOWED_PARENT_ORIGINS = [
  "http://localhost:3001", // client-a
  "http://localhost:3002", // client-b
  "http://localhost:3003", // client-c
  "https://client-a.com",
  "https://client-b.com",
  "https://client-c.com",
];

// Strict message types
type MessageType =
  | "WIDGET_READY"
  | "REQUEST_ACCOUNTS"
  | "SWITCH_ACCOUNT"
  | "LOGOUT_APP"
  | "LOGOUT_GLOBAL"
  | "ACCOUNT_SWITCHED"
  | "AUTH_STATE"
  | "ERROR";

interface WidgetMessage {
  type: MessageType;
  nonce: string; // Generated by sender, echoed back by receiver
  requestId: string; // Unique request ID for matching responses
  payload?: Record<string, unknown>;
}

// ============================================================================
// State Management
// ============================================================================

class WidgetState {
  accounts: Array<{ id: string; name: string; email: string; isPrimary: boolean }> = [];
  activeAccountId: string | null = null;
  isLoading = false;
  thirdPartyCookiesBlocked = false;
  lastRequestId: string | null = null;

  reset() {
    this.accounts = [];
    this.activeAccountId = null;
    this.isLoading = false;
  }
}

const state = new WidgetState();

// ============================================================================
// Utility: Generate Nonce & Request ID
// ============================================================================

function generateNonce(): string {
  return crypto.randomBytes(16).toString("hex");
}

function generateRequestId(): string {
  return crypto.randomBytes(16).toString("hex");
}

// ============================================================================
// Utility: CSRF Token Management
// ============================================================================

function getCSRFToken(): string | null {
  // Read __csrf cookie set by IDP
  const token = document.cookie
    .split("; ")
    .find((row) => row.startsWith("__csrf="))
    ?.split("=")[1];

  if (!token) {
    console.warn("[Widget] CSRF token missing from cookies");
    return null;
  }

  return decodeURIComponent(token);
}

function detectThirdPartyCookieBlock(): boolean {
  // If __csrf cookie not readable, third-party cookies likely blocked
  const csrfToken = getCSRFToken();
  return !csrfToken;
}

// ============================================================================
// Utility: Button Lock (Prevent Spam)
// ============================================================================

class ButtonLock {
  private lockedButtons = new Set<HTMLButtonElement>();

  lock(button: HTMLButtonElement) {
    button.disabled = true;
    button.style.opacity = "0.5";
    button.style.cursor = "not-allowed";
    this.lockedButtons.add(button);
  }

  unlock(button: HTMLButtonElement) {
    button.disabled = false;
    button.style.opacity = "1";
    button.style.cursor = "pointer";
    this.lockedButtons.delete(button);
  }

  unlockAll() {
    this.lockedButtons.forEach((button) => {
      button.disabled = false;
      button.style.opacity = "1";
      button.style.cursor = "pointer";
    });
    this.lockedButtons.clear();
  }
}

const buttonLock = new ButtonLock();

// ============================================================================
// PostMessage: Send Message to Parent with Validation
// ============================================================================

function sendMessageToParent(message: WidgetMessage) {
  if (!window.parent || window.parent === window) {
    console.warn("[Widget] No parent window to send message to");
    return;
  }

  // Only send to allowed origins
  const targetOrigin = document.referrer
    ? new URL(document.referrer).origin
    : document.location.origin;

  if (!ALLOWED_PARENT_ORIGINS.includes(targetOrigin)) {
    console.warn("[Widget] Parent origin not in allowlist:", targetOrigin);
    return;
  }

  window.parent.postMessage(message, targetOrigin);
}

function receiveMessage(handler: (msg: WidgetMessage) => void) {
  window.addEventListener("message", (event) => {
    // 1. Validate origin is in allowlist
    if (!ALLOWED_PARENT_ORIGINS.includes(event.origin)) {
      console.warn("[Widget] Message from untrusted origin:", event.origin);
      return;
    }

    // 2. Validate message structure
    const msg = event.data as WidgetMessage;
    if (!msg.type || !msg.nonce || !msg.requestId) {
      console.warn("[Widget] Invalid message structure:", event.data);
      return;
    }

    // 3. Validate message type
    const validTypes: MessageType[] = [
      "WIDGET_READY",
      "REQUEST_ACCOUNTS",
      "SWITCH_ACCOUNT",
      "LOGOUT_APP",
      "LOGOUT_GLOBAL",
    ];
    if (!validTypes.includes(msg.type)) {
      console.warn("[Widget] Unknown message type:", msg.type);
      return;
    }

    handler(msg);
  });
}

// ============================================================================
// IDP API Calls (Widget talks ONLY to IDP)
// ============================================================================

async function fetchSessionValidate(): Promise<{
  success: boolean;
  user?: { id: string; email: string; name: string };
  account?: { id: string; name: string; email: string };
  accounts?: Array<{ id: string; name: string; email: string; isPrimary: boolean }>;
  activeAccountId?: string;
  error?: string;
}> {
  try {
    // Check if third-party cookies blocked
    if (detectThirdPartyCookieBlock()) {
      console.warn("[Widget] Third-party cookies blocked - cannot call IDP");
      state.thirdPartyCookiesBlocked = true;
      return {
        success: false,
        error: "Third-party cookies blocked",
      };
    }

    const csrfToken = getCSRFToken();
    if (!csrfToken) {
      return {
        success: false,
        error: "No CSRF token available",
      };
    }

    const response = await fetch(`${IDP_URL}/api/auth/session/validate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include", // Include IDP cookies
      body: JSON.stringify({
        _csrf: csrfToken,
      }),
    });

    if (!response.ok) {
      return {
        success: false,
        error: `HTTP ${response.status}`,
      };
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error("[Widget] Session validate error:", error);
    return {
      success: false,
      error: String(error),
    };
  }
}

async function switchAccount(accountId: string): Promise<{ success: boolean; error?: string }> {
  try {
    if (detectThirdPartyCookieBlock()) {
      return {
        success: false,
        error: "Third-party cookies blocked",
      };
    }

    const csrfToken = getCSRFToken();
    if (!csrfToken) {
      return {
        success: false,
        error: "No CSRF token",
      };
    }

    const response = await fetch(`${IDP_URL}/api/auth/switch-account`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
      body: JSON.stringify({
        accountId,
        _csrf: csrfToken,
      }),
    });

    if (!response.ok) {
      return {
        success: false,
        error: `HTTP ${response.status}`,
      };
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error("[Widget] Switch account error:", error);
    return {
      success: false,
      error: String(error),
    };
  }
}

async function logoutApp(clientId: string): Promise<{ success: boolean; error?: string }> {
  try {
    const csrfToken = getCSRFToken();
    if (!csrfToken) {
      return {
        success: false,
        error: "No CSRF token",
      };
    }

    const response = await fetch(`${IDP_URL}/api/auth/logout`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
      body: JSON.stringify({
        scope: "app",
        clientId,
        _csrf: csrfToken,
      }),
    });

    if (!response.ok) {
      return {
        success: false,
        error: `HTTP ${response.status}`,
      };
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error("[Widget] Logout app error:", error);
    return {
      success: false,
      error: String(error),
    };
  }
}

async function logoutGlobal(): Promise<{ success: boolean; error?: string }> {
  try {
    const csrfToken = getCSRFToken();
    if (!csrfToken) {
      return {
        success: false,
        error: "No CSRF token",
      };
    }

    const response = await fetch(`${IDP_URL}/api/auth/logout`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
      body: JSON.stringify({
        scope: "global",
        _csrf: csrfToken,
      }),
    });

    if (!response.ok) {
      return {
        success: false,
        error: `HTTP ${response.status}`,
      };
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error("[Widget] Logout global error:", error);
    return {
      success: false,
      error: String(error),
    };
  }
}

// ============================================================================
// Widget Message Handlers
// ============================================================================

function handleRequestAccounts(msg: WidgetMessage) {
  // Parent requesting current accounts list
  (async () => {
    const result = await fetchSessionValidate();

    if (result.success && result.accounts) {
      state.accounts = result.accounts;
      state.activeAccountId = result.activeAccountId || null;

      sendMessageToParent({
        type: "AUTH_STATE",
        nonce: msg.nonce,
        requestId: msg.requestId,
        payload: {
          accounts: state.accounts,
          activeAccountId: state.activeAccountId,
          user: result.user,
          account: result.account,
        },
      });
    } else if (detectThirdPartyCookieBlock()) {
      // Third-party cookies blocked - notify parent
      sendMessageToParent({
        type: "ERROR",
        nonce: msg.nonce,
        requestId: msg.requestId,
        payload: {
          error: "Third-party cookies blocked",
          thirdPartyCookiesBlocked: true,
        },
      });
    } else {
      sendMessageToParent({
        type: "ERROR",
        nonce: msg.nonce,
        requestId: msg.requestId,
        payload: {
          error: result.error || "Failed to fetch accounts",
        },
      });
    }
  })();
}

function handleSwitchAccount(msg: WidgetMessage) {
  const { accountId } = msg.payload || {};

  if (!accountId) {
    sendMessageToParent({
      type: "ERROR",
      nonce: msg.nonce,
      requestId: msg.requestId,
      payload: { error: "Missing accountId" },
    });
    return;
  }

  // Lock buttons to prevent spam
  const buttons = document.querySelectorAll("button[data-action='switch']");
  buttons.forEach((btn) => buttonLock.lock(btn as HTMLButtonElement));

  (async () => {
    try {
      const result = await switchAccount(accountId as string);

      if (result.success) {
        // Account switched successfully
        // Parent will call /api/me to get new account data
        sendMessageToParent({
          type: "ACCOUNT_SWITCHED",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: {
            activeAccountId: accountId,
          },
        });
      } else {
        sendMessageToParent({
          type: "ERROR",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: { error: result.error || "Switch failed" },
        });
      }
    } finally {
      // Unlock buttons
      buttons.forEach((btn) => buttonLock.unlock(btn as HTMLButtonElement));
    }
  })();
}

function handleLogoutApp(msg: WidgetMessage) {
  const { clientId } = msg.payload || {};

  if (!clientId) {
    sendMessageToParent({
      type: "ERROR",
      nonce: msg.nonce,
      requestId: msg.requestId,
      payload: { error: "Missing clientId" },
    });
    return;
  }

  const buttons = document.querySelectorAll("button[data-action='logout-app']");
  buttons.forEach((btn) => buttonLock.lock(btn as HTMLButtonElement));

  (async () => {
    try {
      const result = await logoutApp(clientId as string);

      if (result.success) {
        sendMessageToParent({
          type: "AUTH_STATE",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: {
            loggedOut: true,
            scope: "app",
          },
        });
      } else {
        sendMessageToParent({
          type: "ERROR",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: { error: result.error || "Logout failed" },
        });
      }
    } finally {
      buttons.forEach((btn) => buttonLock.unlock(btn as HTMLButtonElement));
    }
  })();
}

function handleLogoutGlobal(msg: WidgetMessage) {
  const buttons = document.querySelectorAll("button[data-action='logout-global']");
  buttons.forEach((btn) => buttonLock.lock(btn as HTMLButtonElement));

  (async () => {
    try {
      const result = await logoutGlobal();

      if (result.success) {
        sendMessageToParent({
          type: "AUTH_STATE",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: {
            loggedOut: true,
            scope: "global",
          },
        });
      } else {
        sendMessageToParent({
          type: "ERROR",
          nonce: msg.nonce,
          requestId: msg.requestId,
          payload: { error: result.error || "Logout failed" },
        });
      }
    } finally {
      buttons.forEach((btn) => buttonLock.unlock(btn as HTMLButtonElement));
    }
  })();
}

// ============================================================================
// Widget Initialization
// ============================================================================

export function initializeWidget() {
  // Check third-party cookies on init
  if (detectThirdPartyCookieBlock()) {
    console.warn("[Widget] Third-party cookies blocked on init");
    state.thirdPartyCookiesBlocked = true;
    showFallbackUI();
    return;
  }

  // Set up message listener
  receiveMessage((msg) => {
    switch (msg.type) {
      case "REQUEST_ACCOUNTS":
        handleRequestAccounts(msg);
        break;
      case "SWITCH_ACCOUNT":
        handleSwitchAccount(msg);
        break;
      case "LOGOUT_APP":
        handleLogoutApp(msg);
        break;
      case "LOGOUT_GLOBAL":
        handleLogoutGlobal(msg);
        break;
      default:
        console.warn("[Widget] Unknown message type:", msg.type);
    }
  });

  // Notify parent that widget is ready
  const nonce = generateNonce();
  const requestId = generateRequestId();

  sendMessageToParent({
    type: "WIDGET_READY",
    nonce,
    requestId,
    payload: {
      idpUrl: IDP_URL,
    },
  });
}

// ============================================================================
// Fallback UI (Third-Party Cookies Blocked)
// ============================================================================

function showFallbackUI() {
  const container = document.getElementById("widget-container");
  if (!container) return;

  container.innerHTML = `
    <div style="
      padding: 16px;
      background: #fff3cd;
      border: 1px solid #ffc107;
      border-radius: 4px;
      text-align: center;
    ">
      <p style="margin: 0 0 12px 0; font-size: 14px; color: #333;">
        Your browser blocks third-party cookies. Click to manage accounts:
      </p>
      <button 
        style="
          padding: 8px 16px;
          background: #0d6efd;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-size: 14px;
        "
        onclick="window.open('${IDP_URL}/u/accounts', '_blank')"
      >
        Switch Accounts in New Tab
      </button>
    </div>
  `;
}

// ============================================================================
// Export for use in HTML
// ============================================================================

if (typeof window !== "undefined") {
  const windowObj = window as unknown as Record<string, unknown>;
  windowObj.WidgetAccountSwitcher = {
    init: initializeWidget,
  };
}

